// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Button(props) {
  var className = "rounded-md px-4 py-8 w-64 text-5xl " + props.className;
  return JsxRuntime.jsx("button", {
              children: props.text,
              className: className,
              onClick: props.onClick
            });
}

var make = Button;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
