// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "./Button.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Controls(props) {
  var startButton = JsxRuntime.jsx(Button.make, {
        text: "Start",
        className: "bg-sky-400 text-white hover:bg-sky-500 hover:shadow-md",
        onClick: props.onStartClick
      });
  var activeButton = JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx(Button.make, {
                text: "Reset",
                className: "bg-yellow-400 text-white hover:bg-yellow-500 hover:shadow-md",
                onClick: props.onResetClick
              }),
          JsxRuntime.jsx(Button.make, {
                text: props.isPaused ? "Resume" : "Pause",
                className: "bg-gray-400 text-white hover:bg-gray-500 hover:shadow-md",
                onClick: props.onPauseResumeClick
              })
        ],
        className: "flex justify-between gap-2 "
      });
  return JsxRuntime.jsx("div", {
              children: props.isActive ? activeButton : startButton,
              className: "mx-auto"
            });
}

var make = Controls;

export {
  make ,
}
/* Button Not a pure module */
