// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Digit(props) {
  var className = "inline-block text-9xl" + props.className;
  return JsxRuntime.jsx("span", {
              children: props.digit,
              className: className
            });
}

var make = Digit;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
