// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Digit from "./Digit.res.mjs";
import * as Formatter from "../utils/Formatter.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Timer(props) {
  var time = props.time;
  var d1 = Formatter.formatD1(time);
  var d2 = Formatter.formatD2(time);
  var d3 = Formatter.formatD3(time);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Digit.make, {
                      digit: d1,
                      className: ""
                    }),
                JsxRuntime.jsx(Digit.make, {
                      digit: ":",
                      className: ""
                    }),
                JsxRuntime.jsx(Digit.make, {
                      digit: d2,
                      className: ""
                    }),
                JsxRuntime.jsx(Digit.make, {
                      digit: ":",
                      className: ""
                    }),
                JsxRuntime.jsx(Digit.make, {
                      digit: d3,
                      className: ""
                    })
              ]
            });
}

var make = Timer;

export {
  make ,
}
/* Digit Not a pure module */
