// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Timer from "./components/Timer.res.mjs";
import * as React from "react";
import * as Controls from "./components/Controls.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return false;
      });
  var setIsActive = match[1];
  var isActive = match[0];
  var match$1 = React.useState(function () {
        return true;
      });
  var setIsPaused = match$1[1];
  var isPaused = match$1[0];
  var match$2 = React.useState(function () {
        return 0;
      });
  var setTime = match$2[1];
  React.useEffect((function () {
          var interval = {
            contents: undefined
          };
          var exit = 0;
          if (isActive && !isPaused) {
            var id = setInterval((function () {
                    setTime(function (time) {
                          return time + 10 | 0;
                        });
                  }), 10);
            interval.contents = Caml_option.some(id);
          } else {
            exit = 1;
          }
          if (exit === 1) {
            var interval$1 = interval.contents;
            if (interval$1 !== undefined) {
              clearInterval(Caml_option.valFromOption(interval$1));
            }
            
          }
          return (function () {
                    var interval$2 = interval.contents;
                    if (interval$2 !== undefined) {
                      clearInterval(Caml_option.valFromOption(interval$2));
                      return ;
                    }
                    
                  });
        }), [
        isActive,
        isPaused
      ]);
  var handleStart = function (_e) {
    setIsActive(function (_prev) {
          return true;
        });
    setIsPaused(function (_prev) {
          return false;
        });
  };
  var handlePauseResume = function (_e) {
    setIsPaused(function (prev) {
          return !prev;
        });
  };
  var handleReset = function (_e) {
    setIsActive(function (_prev) {
          return false;
        });
    setTime(function (_prev) {
          return 0;
        });
  };
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("h1", {
                            children: "Rescript stopwatch",
                            className: "mb-12 flex justify-center text-semibold text-6xl text-white"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx(Timer.make, {
                                    time: match$2[0]
                                  }),
                              JsxRuntime.jsx(Controls.make, {
                                    isActive: isActive,
                                    isPaused: isPaused,
                                    onStartClick: handleStart,
                                    onResetClick: handleReset,
                                    onPauseResumeClick: handlePauseResume
                                  })
                            ],
                            className: "h-80  border border-white rounded-xl text-white shadow-xl flex flex-col justify-between p-8"
                          })
                    ],
                    className: " container mx-auto flex flex-col justify-center items-center "
                  }),
              className: "bg-red-500  flex justify-center h-screen"
            });
}

var make = App;

export {
  make ,
}
/* Timer Not a pure module */
